name: CI - Continuous Integration

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: test
          POSTGRES_PASSWORD: test
          POSTGRES_DB: testdb
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U test"
          --health-timeout=30s
          --health-interval=5s
          --health-retries=3

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "22.11.0"

      - name: Install dependencies
        run: npm install

      - name: Wait for PostgreSQL to be ready
        run: |
          until pg_isready -h localhost -p 5432 -U test; do
            echo "Waiting for PostgreSQL to be ready..."
            sleep 2
          done

      - name: Load environment variables from .env
        run: |
          echo "DATABASE_URL=postgresql://test:test@localhost:5432/testdb?schema=public" >> $GITHUB_ENV
          echo "JWT_SECRET=18f0e27bcb06d53dee5c34ebc7366702b36b2d66" >> $GITHUB_ENV

      - name: Set up Prisma
        run: |
          npx prisma migrate deploy
          npx prisma generate
          npx prisma migrate status # Verifica se as migrações foram aplicadas corretamente

      - name: Run tests
        run: npm test
